services:
  db:
    container_name: postgres_e_house
    image: postgres
    environment:
      POSTGRES_USER: house
      POSTGRES_PASSWORD: house
      PGDATA: /data/postgres
      POSTGRES_DB: e_house_suite
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  test_db:
    container_name: postgres_e_house_test
    image: postgres
    environment:
      POSTGRES_USER: house
      POSTGRES_PASSWORD: house
      PGDATA: /data/postgres
      POSTGRES_DB: e_house_suite_test
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5323:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: